name: bar_file_compile

on:
  workflow_dispatch:
    inputs:
      flow_name:
        type: string
        required: true
        description: 'Enter the Application Name for Bar file Creation'

jobs:
  checkout_SCM:
   runs-on: [iibtest-01]
   steps:
     - name: test_login
       run: |
         echo "hostname of the VM is: $HOSTNAME"
     
     - name: Checkout
       uses: actions/checkout@v1
        
     - name: List_Dir_After_Checkout
       run: |
         pwd
         ls -alrt
         echo "The GitHub Repo Name is: ${{ github.event.repository.name }}"
         echo "The selected input variable is: ${{ github.event.inputs.flow_name }}"
         echo "The Branch info: ${{ github.ref_name }}"
         echo "The Working Directory info: ${GITHUB_WORKSPACE}"

  bar_file_creation:
    runs-on: [iibtest-01]
    needs: checkout_SCM
    steps:
      - name: create_barfile
        run: |
          cd ${GITHUB_WORKSPACE}
          mkdir tmp && cd tmp
          pwd
          cp -R ${GITHUB_WORKSPACE}/esed_src/IIB_COMMON_LIB/EDIS* .
          cp -R ${GITHUB_WORKSPACE}/esed_src/IIB_SRC/${{ github.event.inputs.flow_name }}/src/*.* .
          ls -lrt
          mqsicreatebar -data . -b ${{ github.event.inputs.flow_name }}.bar -a ${{ github.event.inputs.flow_name }} -skipWsErrorCheck -deployAsSource
          ls -lrt
