name: bar_file_compile

on:
  workflow_dispatch:
    inputs:
      flow_name:
        type: string
        required: true
        description: 'Enter the Application Name for Bar file Creation'

jobs:
  checkout_SCM:
   runs-on: [iibtest-01]
   steps:
     - name: test_login
       run: |
         echo "hostname of the VM is: $HOSTNAME"
     
     - name: Checkout
       uses: actions/checkout@v1
        
     - name: List_Dir_After_Checkout
       run: |
         pwd
         ls -alrt
         echo "The GitHub Repo Name is: ${{ github.event.repository.name }}"
         echo "The selected input variable is: ${{ github.event.inputs.flow_name }}"
         echo "The Branch info: ${{ github.ref_name }}"
         echo "The Working Directory info: ${GITHUB_WORKSPACE}"

  bar_file_creation:
    runs-on: [iibtest-01]
    needs: checkout_SCM
    permissions:
      issues: write
      contents: write
      packages: write
    steps:
      - name: create_barfile
        run: |
          echo "you are running as $(whoami) User"
          cd ${GITHUB_WORKSPACE}
          mkdir tmp && cd tmp
          pwd
          cp -R ${GITHUB_WORKSPACE}/esed_src/IIB_COMMON_LIB/EDIS* .
          cp -R ${GITHUB_WORKSPACE}/esed_src/IIB_SRC/${{ github.event.inputs.flow_name }}/src/* .
          ls -lrt
          xvfb-run --auto-servernum --server-num=1 /home/jnell16/ace-12.0.7.0/tools/mqsicreatebar -data . -b ${{ github.event.inputs.flow_name }}.bar -a ${{ github.event.inputs.flow_name }} -skipWsErrorCheck -deployAsSource -trace
          ls -lrt
      
      - name: read_created_barfile
        run: |
          cd ${GITHUB_WORKSPACE}/tmp
          /home/jnell16/ace-12.0.7.0/server/bin/mqsireadbar -b ${{ github.event.inputs.flow_name }}.bar -r
      
      - name: Upload_barfile_Github
        run: |
          cd ${GITHUB_WORKSPACE}/tmp
          mkdir repo && cd repo
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config user.email "mqsi@bot.com"
          git config user.name "mqsi"
          git fetch
          git checkout ${{ github.ref_name }}
          git branch --set-upstream-to=origin/${{ github.ref_name }}
          git pull
          ls -a
          cp /home/jnell16/workspace/IIB_Sourcecode/IIB_Sourcecode/tmp/${{ github.event.inputs.flow_name }}.bar /home/jnell16/workspace/IIB_Sourcecode/IIB_Sourcecode/tmp/repo/esed_std/ESEDA
          echo "${{ github.event.inputs.flow_name }}.bar file is moved to the ESEDA Folder..."
          ls -a
          git add -A
          git commit -m "Commit bar ${{ github.event.inputs.flow_name }}.bar file"
          git push


